name: "Microsoft Graph Calendar"
description: "Display your Microsoft Graph Calendar in Home Assistant"
version: "0.0.1"
slug: "home_assistant_ms_graph"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8080/tcp: 8080