name: "M365 Calendar"
description: "Display your Microsoft365 Calendar in Home Assistant using the Microsoft Graph API"
version: "0.0.2"
slug: "home_assistant_ms_graph"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  7200/tcp: 8080
ingress: true
ingress_port: 7200