name: "Home Assistant Microsoft Graph Add-on"
description: "My first real add-on!"
version: "1.0.0"
slug: "home_assistant_ms_graph"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386